# The equivalent memory usage is 891MB if we assumed that each column is a string of 50 bytes (rough estimate)

data<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
data$Date<-as.Date(data$Date,"%d/%m/%Y")
start_date<-as.Date("01/02/2007","%d/%m/%Y")
end_date<-as.Date("02/02/2007","%d/%m/%Y")
data<-subset(data,Date<=end_date & Date>= start_date)
data$Time<-format(strptime(data$Time,format="%T"),format="%H:%M:%S")
png(filename="plot3.png",width=480,height=480,units="px")
with(data,plot(as.POSIXct(paste(Date,Time)),as.numeric(Sub_metering_1),main="Global Active Power",col="black",type="l",xlab="",ylab="Global Active Power (kilowatts)"))
lines(as.POSIXct(paste(data$Date,data$Time)),data$Sub_metering_2,col="red")
lines(as.POSIXct(paste(data$Date,data$Time)),data$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1)
dev.off()